### ISSUE TITLE
I have issue with sever member box not looking way it shoaled be

### ISSUE THREAD

**Issue by stoneshout** [Saltssaumure/w9x-discord-theme#16]
![cae875de615a17aaaf5cc96a76f3c1b5](https://github.com/Saltssaumure/w9x-discord-theme/assets/121679878/725c1caa-cd71-402c-9330-7919c0d496c9)
no idea how to fix this even tryd it with no plugins on still looks like this didn't look like this yesterday

**Comment by Saltssaumure** [comment]
Thanks for the heads up. Discord updated some classes here, I'll get it fixed soon.

**Comment by stoneshout** [comment]
thank you
