### ISSUE TITLE
text doesn't appear when type

### ISSUE THREAD

**Issue by 4ourpj** [Saltssaumure/w9x-discord-theme#20]
when typing, text wont appear unless highlighted
im not sure why this happen

![the](https://github.com/Saltssaumure/w9x-discord-theme/assets/134241013/ca647799-79c5-4194-84dc-67d68dba4286)

**Comment by Saltssaumure** [comment]
Are you using any plugins that affect the typing box, or have the BDFDB plugin library?

**Comment by 4ourpj** [comment]
i only have the bdfdb plugin

**Comment by 4ourpj** [comment]
even with disabling every plugin, the problem persist

**Comment by Saltssaumure** [comment]
The problem is caused by having BDFDB present in the plugins folder at all. You need to delete it or move it to another folder, then fully restart Discord.

**Comment by 4ourpj** [comment]
I have restarted and removed BDFDB, however the problem persists. However, if I were to switch to light mode the text would appear but not for dark. I also tried reinstalling from Github as well.

(Reinstalling Discord as well doesn't work.)

**Comment by Saltssaumure** [comment]
Cannot reproduce issue except by suggested solution, closed for now.
