### ISSUE TITLE
Profiles with darker themes unreadable

### ISSUE THREAD

**Issue by LabAviator** [Saltssaumure/w9x-discord-theme#22]
Using the latest version of NineX available on Themes site on BetterDiscord and installed alongside with BetterDiscord, I have noticed that any profile with a darker profile theme becomes nigh unreadable as the theme will still use black text on a dark background.

I'm not sure how customizable this is, but if possible I'd recommend to switch to white text on darker profile themes.

Here is an example image of my own profile only using a custom profile theme colour and accent (no profile effect or decoration):

![Untitled](https://github.com/Saltssaumure/w9x-discord-theme/assets/31162832/a2498e7d-591f-4d4f-9311-6092ef4ae1d5)

**Comment by Saltssaumure** [comment]
This is probably a bug due to a recent Discord update, will fix soon.
