### ISSUE TITLE
Self profile popup appears offscreen

### ISSUE THREAD

**Issue by Yaiko223** [Saltssaumure/w9x-discord-theme#25]
profile is not displayed correctly
![Снимок экрана 2024-06-21 100056](https://github.com/Saltssaumure/w9x-discord-theme/assets/160311016/a3675d48-3285-4522-a391-10c1b25c3c7c)

**Comment by Saltssaumure** [comment]
Tested, bug seems to be intermittent and resolves itself after closing and reopening the user profile.
