### ISSUE TITLE
GIF Outlines are oversized

### ISSUE THREAD

**Issue by Ben-Brady** [Saltssaumure/w9x-discord-theme#3]
The outlines for gifs are fixed sized and over extend pass the bounds of the gif, doesn't apply to images. Not sure if this is intentional or not.
![image](https://user-images.githubusercontent.com/64110708/232210736-17f570a3-487e-40ac-9d16-54de0c1da4c8.png)

**Comment by Saltssaumure** [comment]
Not intentional, thanks for reporting!
