### ISSUE TITLE
[Message Box] Glitched Buttons

### ISSUE THREAD

**Issue by ZackyGameDev** [Saltssaumure/w9x-discord-theme#4]
In the discord message send box, there are many buttons, e.g. the "Gift" button, "Send Message Button", "Stickers", and other buttons created by Plugins.
However, some of them break and/or appear a bit messed up when this theme is turned on.

## Without the theme
![image](https://user-images.githubusercontent.com/58615455/233253127-ebe21f58-369c-44d6-bf09-0652213ce850.png)

## With the theme in Dark Mode
![image](https://user-images.githubusercontent.com/58615455/233253411-74609a9c-0b69-4f09-989d-ac2a38bc392c.png)

## With the theme in Light Mode
![image](https://user-images.githubusercontent.com/58615455/233253362-6dc5ba0b-fd5b-4809-bbdb-661237b96f6a.png)

**Comment by Saltssaumure** [comment]
Which plugins add those buttons?

**Comment by ZackyGameDev** [comment]
The "send message" and "send stickers" buttons are discord native.
The calendar looking icon in my screenshots is the "Send timestamp" button, by the plugin "Send Timestamps"

**Comment by Saltssaumure** [comment]
The version of SendTimestamps on the BD store no longer works: https://betterdiscord.app/plugin/SendTimestamps
Where did you get your version from, so that I can test?

**Comment by ZackyGameDev** [comment]
I'm actually using [Vencord](https://github.com/Vencord/Installer/releases), the `Send Timestamps` plugin in the Vencord plugin library still happens to work.
I did some testing, and it appears that this bug can be reproduced using the following plugins with BetterDiscord: [Translator](https://betterdiscord.app/plugin/Translator), [InvisibleTyping](https://betterdiscord.app/plugin/InvisibleTyping), or any other plugin that introduces a new button in the message box.
The send message button seems to be bugged in general, even without any plugins
