### ISSUE TITLE
Incompatible with Evelyn's SpotifyModal plugin

### ISSUE THREAD

**Issue by nguyenle2457** [Saltssaumure/w9x-discord-theme#5]
I'm using Replugged with this theme (very nice theme btw thank you) and if [SpotifyModal](https://github.com/Socketlike/SpotifyModal) is enabled, the entire bottom right corner, where voice buttons, settings and profile reside, is replaced by the modal, effectively disabling all of that and most importantly locking you out of accessing Settings if you happen to be listening to Spotify.

**Comment by Saltssaumure** [comment]
Fixed 2a30de0088d1791a1c8e8a6007035fe58130826f
