### ISSUE TITLE
Group DMS and DM - calling box is too big and prevents typing.

### ISSUE THREAD

**Issue by DrekAnon** [Saltssaumure/w9x-discord-theme#6]
![oxVn11l](https://github.com/Saltssaumure/w9x-discord-theme/assets/15722018/19829a09-d3b1-4125-b5ca-9c32d99dceab)
Box is too large and there's no way to resize it as far as I can tell, help?

**Comment by Saltssaumure** [comment]
Can't replicate at the moment, this is what I see in group calls:
![image](https://github.com/Saltssaumure/w9x-discord-theme/assets/29710355/5d69f326-9138-4c00-95c2-4d2af29ef795)

Could you provide the following info please:
- Client mod used (BetterDiscord, Replugged, Vencord, etc)
- Theme version

**Comment by Saltssaumure** [comment]
Closing as unreplicable for now.
