### ISSUE TITLE
Headings have the incorrect colour

### ISSUE THREAD

**Issue by sxxov** [Saltssaumure/w9x-discord-theme#7]
## Overview

Headings seem to have the same colour as the background, causing them to take up space but not show up:

### Raw Message Content
```md
# AI
Prevent false negatives via past data

## Difference from Ass 1

### Functionality
* Add data collection from nodes
* Add categorising AI running on server

### UI
```

### Result

|Message with headings|Message with headings, highlighted|
|-|-|
|<img width="304" alt="image" src="https://github.com/Saltssaumure/w9x-discord-theme/assets/50891910/7c5e05a1-e51d-4613-994e-4e4c4c965a17">|<img width="299" alt="image" src="https://github.com/Saltssaumure/w9x-discord-theme/assets/50891910/88a01ff9-0ee5-48e6-be86-7a541497c2aa">|

---

## Related Information

[Discord Docs: Organizational Text Formatting](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-#h_01GY0DB14X1PFY87CJFFVHFW4T)

---

## Version Information

```
Stable 203670 (1d87dbe)
Vencord 55543d8 (Standalone)
Electron 22.3.2
Chromium 108.0.5359.215
Host 1.0.9013 (32266)
OpenAsar Nightly (cd44357)
```

**Comment by Plaer1** [comment]
for now you can add this to your theme css (settings)
```
h1, h2 {
    color: #DFDFDF !important;
}
```
