### ISSUE TITLE
Suggestion: Make text of channel name different when channel is muted.

### ISSUE THREAD

**Issue by Fallen-Feces** [Saltssaumure/w9x-discord-theme#8]
Title says it all. A feature like this is kind of a dealbreaker as to whether or not I use a theme.

**Comment by Saltssaumure** [comment]
Added:
![image](https://github.com/Saltssaumure/w9x-discord-theme/assets/29710355/d99c8b42-50ed-4cf7-a352-9f92f52759a1)
